name: android_notifications
description: A Flutter plugin for managing notification on Android Platform.
version: 0.0.3
author: Lenox <nikeorever@gmail.com>
homepage: https://github.com/nikeorever/android_notifications

environment:
  sdk: ">=2.1.0 <3.0.0"
  # Flutter versions prior to 1.12 did not support the
  # flutter.plugin.platforms map.
  flutter: ">=1.12.0 <2.0.0"


dependencies:
  flutter:
    sdk: flutter
  platform: ^2.2.1
  meta: ^1.2.3

dev_dependencies:
  test: ^1.3.0
  mockito: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: cn.nikeo.flutter.plugins.androidnotifications
        pluginClass: AndroidNotificationsPlugin
