name: android_notifications
description: Flutter plugin for display notifications, Not supported on iOS
version: 0.0.2
author: Nikeo <nikeorever@gmail.com>
homepage: https://github.com/nikeorever/android_notifications

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  platform: ^2.2.1
  meta: ^1.0.5

dev_dependencies:
  test: ^1.3.0
  mockito: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.nikeorever.flutter.plugins.androidnotifications
    pluginClass: AndroidNotificationsPlugin
